### ISSUE TITLE
Saving playlist copies to the clipboard a link to /#undefined

### ISSUE THREAD

**Issue by urscion** [LNFWebsite/Streamly#463]
I pause the video and after clicking the Save Playlist button, the following link is copied:

[https://lnfwebsite.github.io/Streamly/#undefined](https://lnfwebsite.github.io/Streamly/#undefined)

instead of an expected playlist link.

**Comment by LNFWebsite** [comment]
Welcome to Streamly and thank you for your bug report.

I'm not able to reproduce this issue in either the latest Chrome or Firefox so I have to ask you for some info:

- Are you using Windows, Mac, or Linux?
- Which browser are you using?
- Is JavaScript enabled on your browser?
- Please provide me an example playlist on which the Save Playlist button is responding with `undefined`.
- If possible, enter developer mode on your browser (probably with `Ctrl+Shift+i` depending on your browser), hit `console`, and reply with the full output.

Thanks again and sorry for this inconvenience!

**Comment by urscion** [comment]
nvm, it seems to work now. must have been on my side.

**Comment by LNFWebsite** [comment]
Thanks for the update!

If you find any other bugs to report or have any suggestions for Streamly, just let me know.
