### ISSUE TITLE
i will love to do copywriting for you 

### ISSUE THREAD

**Issue by Hamzeto938** [LNFWebsite/Streamly#474]
I love your application and would want to contribute to it, I'm not a developer but I am good at copywriting. I would love to make a copywrite for your Readme and make a pull request for you to merge. Your response would be highly appreciated. Also I would like to request if we could communicate via email, so I don't have to create issues. Thank you.

**Comment by LNFWebsite** [comment]
Hi there! Welcome to Streamly.

As always, pull requests from both users and developers are welcomed on my project!

That said, I looked at your commit and issue history and see that you have been posting issues of the exact same wording to other projects. May I ask for what reason you are working on these projects?

Thanks again, and yes you most definitely can make a PR!
