### ISSUE TITLE
free logo/icon design

### ISSUE THREAD

**Issue by Pelikens** [LNFWebsite/Streamly#478]
Hi, my name is Ksenia. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your app. If it's something you're interested in, please, let me know!

**Comment by LNFWebsite** [comment]
Hi there! Welcome to Streamly!

Any and all contributions are welcome on my project! Thanks for the opportunity.

**Comment by Pelikens** [comment]
Hi and thanks for your reply! That's great! Do you have any special requirements for the logo? Any symbols that should be included?  And how do you plan to use the logo? On your web site and  etc?

**Comment by LNFWebsite** [comment]
Not really any special requirements for the logo... Something simplistic that conveys the project's purpose (video streaming). Something that would go well with Streamly's black theme. I'll trust your judgement on what would look nice on the project.

I'll probably be using the logo next to the "Streamly" branding in the upper left of the project along with on the readme and any other user-friendly documentation so multiple resolutions and transparent background SVGs would be great (if possible).

Thanks for reaching out! I look forward to seeing your contribution!

**Comment by Pelikens** [comment]
ok, I'll show you the option, how it's done.

**Comment by Pelikens** [comment]
Hi, here is an option for the logo. Please, let me know what do you think? 
![image](https://user-images.githubusercontent.com/39441298/43059616-fc078daa-8e55-11e8-9209-1f619642f0be.png)
I showed you the options on a dark and light background

**Comment by Pelikens** [comment]
version with your logo 
![image](https://user-images.githubusercontent.com/39441298/43061018-160783c6-8e5c-11e8-8721-5d43fdd47ae0.png)

**Comment by LNFWebsite** [comment]
Excellent job!

Now just submit a pull request with all the necessary files added (you can just drop them in the top level directory, I can move them later)

Thank you for your contribution!

**Comment by Pelikens** [comment]
do we leave the version with your font? I'll open the PR when I make you options of all sizes. color and monochrome, OK? Png, eps, ai, psd - it's ok?

**Comment by Pelikens** [comment]
I uploaded all the required files and created a pull-request. Please merge it if everything is Ok.

**Comment by LNFWebsite** [comment]
Great job! Thanks again for your contribution.

I'll be implementing the new logo into Streamly in the next coming days!
